# permissions for end users to view myapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myapp-viewer-role
rules:
- apiGroups:
  - app.github.com
  resources:
  - myapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.github.com
  resources:
  - myapps/status
  verbs:
  - get
